baseURL: "https://gby.ai/" #ç»‘å®šçš„åŸŸå
title: GbyAI #ç½‘ç«™æ ‡é¢˜
paginate: 10 #é¦–é¡µæ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°
theme: PaperMod #ä¸»é¢˜åç§°
languageCode: zh-cn #é»˜è®¤è¯­è¨€
ignoreErrors: ["error-remote-getjson"]  #yml or ignoreErrors = ["error-remote-getjson"]  #toml
enableRobotsTXT: true # å…è®¸çˆ¬è™«æŠ“å–åˆ°æœç´¢å¼•æ“ï¼Œå»ºè®® true

minify:
  disableXML: true
  minifyOutput: true

# ç½‘é¡µä¸‹æ–¹copyrightè¯´æ˜
copyright: Content under license [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)

#æœç´¢ä½¿ç”¨
outputs:
  home:
      - HTML
      - RSS
      - JSON # is necessary

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: GbyAI
  description: "æ¢ç´¢AIGCï¼Œäº†è§£æ·±å±‚çš„agentè½åœ°ï¼Œæ¢ç´¢promptçš„å®é™…åº”ç”¨ï¼Œæœ€æ–°çš„AIæ–¹é¢æ¶ˆæ¯ä¼ é€’"
  keywords: ["AIGC", "agent", "prompt", "news"]
  author: ["hellloveyy"]
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2006-01-02"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false #æ˜¯å¦å±•ç¤ºé˜…è¯»æ—¶é—´
  ShowShareButtons: false #æ˜¯å¦å±•ç¤ºè¯„è®ºå’Œåˆ†äº«æŒ‰é’®
  # æ”¯æŒåˆ†äº«çš„å¹³å° X / facebook / reddit / telegram / whatsapp / ycombinator / linkedin
#  ShareButtons:
#    - x
#    - telegram
#    - email
  ShowPostNavLinks: true
  ShowBreadCrumbs: false #æ˜¯å¦å±•ç¤ºé¢åŒ…å±‘å¯¼èˆª
  ShowCodeCopyButtons: true #ä»£ç æ˜¯å¦å±•ç¤ºcopyæŒ‰é’®
  ShowWordCount: false #æ˜¯å¦å±•ç¤ºå­—æ•°ç»Ÿè®¡
  ShowRssButtonInSectionTermList: true #è®¢é˜…æŒ‰é’®
  UseHugoToc: true
  ViewCount: false # æ˜¯å¦å±•ç¤º uvã€pv
#  BaiduAnalytics: "" # æ˜¯å¦å¼€å¯ç™¾åº¦ç»Ÿè®¡
  #googleAnalytics:  # è°·æ­Œç»Ÿè®¡
  disableSpecial1stPost: false
  disableScrollToTop: false #æ»‘åŠ¨åˆ°é¡¶éƒ¨
  comments: false #è¯„è®ºå±•ç¤º
  hidemeta: false
  hideSummary: true
  hideDescription: true
  showtoc: true #æ˜¾ç¤ºç›®å½•
  tocopen: true #è‡ªåŠ¨å±•å¼€ç›®å½•
  # ç½‘ç«™å·¦ä¸Šè§’çš„æ–‡å­—å’Œå›¾æ ‡é…ç½®
  label:
    text:
    iconSVG:

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari_pinned_tab.png"

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # ç½‘ç«™ä»‹ç»
  homeInfoParams:
    Title: "Hi! I'm hellloveyy \U0001F44B"
    Content: "ä¸€åå…¨èº«å¿ƒæŠ•å…¥ AIGC çš„å­¦å¾’ - **[è¿›ä¸€æ­¥äº†è§£æˆ‘](/about)**"

  socialIcons:
#     - name: wechat
#       url: "https://www.beizigen.com/images/wechat.webp"
    - name: email
      url: "mailto:hellloveyy@gmail.com"
    - name: github
      url: "https://github.com/hellloveyy"
    - name: rss
      url: "/index.xml"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page
    # åœ¨åˆ—è¡¨é»˜è®¤æ˜¾ç¤ºçš„å›¾ç‰‡
    defaultImage: https://images.unsplash.com/photo-1594193316420-74562b321032?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGdyYWRpZW50JTIwYmxhY2t8ZW58MHwwfDB8fHwy

  editPost:
    URL: "https://github.com/hellloveyy/obsidian-GbyAi/tree/main/content"
    Text: "æŒ‡å‡ºé—®é¢˜" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content", "tags"]

# é€‰æ‹©languageså­—æ®µçš„å“ªä¸ªè¯­è¨€ï¼Œé»˜è®¤ en
defaultContentLanguage: zh
languages:
  zh:
    permalinks:
      # é»˜è®¤ä¼šå¸¦è·¯å¾„ä¼šå¸¦ /posts å‰ç¼€
      posts: /:slug/
    menu:
      main:
        - name: ğŸ”æœç´¢
          url: search
          weight: 1
        - name: ğŸ“šæ–‡ç« 
          url: archives
          weight: 2
        # - name: æ ‡ç­¾
        #   url: tags
        #   weight: 2
        - name: ğŸ§©ç³»åˆ—
          url: series
          weight: 3
        - name: ğŸ¤èµåŠ©
          url: sponsor
          weight: 4
          
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
markup:
  goldmark:
    extensions:
      # ç¦ç”¨ Hugo å°†è‹±æ–‡å•å¼•å·è½¬ä¸º &rsquo
      typographer: false
# highlight:
#   noClasses: false
#   anchorLineNos: true
  # codeFences: true
  # guessSyntax: true
  # lineNos: true
  # style: monokai

taxonomies:
  tag: tags
  series: series
